title: Sahit Chintalapudi
description: I'm an MIT Graduate Student studying motion planning for robotics. 

url: http://chsahit.github.io
baseurl: ""
paginate_path: "projects/page:num/"
permalink: blog/:title/
google_analytics: UA-142700083-1

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: About
   url: /index.html
 - title: Reading
   url: /books/

social:
   github: chsahit
   email: sahit@mit.edu 
   twitter: Sahitbot_iRL
