title: Sahit Chintalapudi
description: A glimpse into my life

url: http://chsahit.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Resume
   url: /resume

social:
   github: chsahit
   email: schintalapudi@gatech.edu
