title: Sahit Chintalapudi
description: A third year computer science major at Georgia Tech who is passionate about robotics.

url: http://chsahit.github.io
baseurl: ""
paginate_path: "projects/page:num/"
permalink: blog/:title/
google_analytics: UA-142700083-1

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: About
   url: /index.html
 - title: Projects
   url: /projects/
 - title: Talks
   url: /talks/index.html
 - title: Reading
   url: /books/

social:
   github: chsahit
   email: schintalapudi@gatech.edu
   twitter: Sahitbot_iRL
